version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: financial-control-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: financial_control
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - financial-network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financial-control-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://admin:password123@mongodb:27017/financial_control?authSource=admin
      - DB_NAME=financial_control
      - JWT_SECRET_KEY=your-super-secure-secret-key-change-in-production
    depends_on:
      - mongodb
    networks:
      - financial-network
    volumes:
      - ./backend:/app:ro  # Read-only for security
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8001/', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend (Optional - for full containerized deployment)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: financial-control-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    depends_on:
      - backend
    networks:
      - financial-network

volumes:
  mongodb_data:
    driver: local

networks:
  financial-network:
    driver: bridge